import type { Issue } from '@/lib/types';

export const initialIssues: Issue[] = [
  {
    id: 'SF-001',
    title: 'Implement user authentication',
    description: 'Users should be able to sign up and log in using email and password.',
    status: 'In Progress',
    priority: 'Urgent',
    assignee: 'Alice Wonderland',
    reporter: 'Project Lead',
    createdAt: new Date(2023, 10, 1).toISOString(),
    updatedAt: new Date(2023, 10, 5).toISOString(),
    dueDate: new Date(2023, 10, 15).toISOString(),
    labels: ['auth', 'backend'],
  },
  {
    id: 'SF-002',
    title: 'Design issue list UI',
    description: 'Create a responsive and user-friendly UI for displaying issues.',
    status: 'To Do',
    priority: 'High',
    assignee: 'Bob The Builder',
    reporter: 'UX Designer',
    createdAt: new Date(2023, 10, 2).toISOString(),
    updatedAt: new Date(2023, 10, 2).toISOString(),
    dueDate: new Date(2023, 10, 20).toISOString(),
    labels: ['ui', 'frontend', 'design'],
  },
  {
    id: 'SF-003',
    title: 'Integrate Google Sheets API for reading data',
    description: 'Connect to Google Sheets to fetch initial issue data.',
    status: 'Backlog',
    priority: 'Medium',
    reporter: 'Project Lead',
    createdAt: new Date(2023, 10, 3).toISOString(),
    updatedAt: new Date(2023, 10, 3).toISOString(),
    labels: ['api', 'backend', 'integration'],
  },
  {
    id: 'SF-004',
    title: 'Fix layout bug on mobile devices',
    description: 'The main content area overflows on smaller screens.',
    status: 'Done',
    priority: 'High',
    assignee: 'Charlie Brown',
    reporter: 'QA Tester',
    createdAt: new Date(2023, 9, 15).toISOString(),
    updatedAt: new Date(2023, 9, 20).toISOString(),
    dueDate: new Date(2023, 9, 18).toISOString(),
    labels: ['bug', 'frontend', 'mobile'],
  },
  {
    id: 'SF-005',
    title: 'Setup CI/CD pipeline',
    description: 'Automate build, test, and deployment processes.',
    status: 'To Do',
    priority: 'Medium',
    assignee: 'Diana Prince',
    reporter: 'DevOps Engineer',
    createdAt: new Date(2023, 10, 8).toISOString(),
    updatedAt: new Date(2023, 10, 8).toISOString(),
    labels: ['devops', 'ci-cd'],
  },
];

export const assignees: string[] = [
  "Alice Wonderland",
  "Bob The Builder",
  "Charlie Brown",
  "Diana Prince",
  "Edward Scissorhands",
  "Fiona Gallagher"
];
